site_name: Vortex
nav:
    - Home : 'index.md'
    - User Guides :
        - 'Dataset Integration' : 'user-guides/dataset_integration.md'
        - 'Experiment File Configuration' : 'user-guides/experiment_file_config.md'
        - 'HypOpt File Configuration' : 'user-guides/hypopt_file_config.md'
        - 'Pipelines' : 'user-guides/pipelines.md'
    - Developer Guides :
        - 'Custom Backbone Integration' : 'developer-guides/custom_backbone_integration.md'
        - 'Custom Model Integration : Classification' : 'developer-guides/custom_model_integration_classification.md'
        - 'Custom Model Integration : Detection' : 'developer-guides/custom_model_integration_detection.md'
    - Modules :
        - 'Built-in Dataset' : 'modules/builtin_dataset.md'
        - 'Logging Provider' : 'modules/logging_provider.md'
        - 'Augmentations' : 'modules/augmentation.md'
        - 'Data Loader' : 'modules/data_loader.md'
        - 'Learning Rates Scheduler' : 'modules/scheduler.md'
        - 'Training Driver' : 'modules/train_driver.md'
        - 'Models Zoo' : 'modules/models_zoo.md'
        - 'Backbones Network' : 'modules/backbones.md'
        - 'Graph Exporter' : 'modules/exporter.md'
    - API :
        - 'vortex.development.pipelines' : 'api/vortex.development.pipelines.md'
        - 'vortex.development.utils.factory' : 'api/vortex.development.utils.factory.md'
        - 'vortex.runtime' : 'api/vortex.runtime.md'
    - Repository : 'https://github.com/nodefluxio/vortex'
markdown_extensions:
    - attr_list
    - toc:
        permalink: True
theme:
    name: mkdocs
    highlightjs: true
    hljs_style: ir-black
    hljs_languages:
        - python
        - console
        - yaml
    navigation_depth: 3