FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /opt/

## install system requirements
COPY requirements.sys requirements.sys
RUN apt update && xargs apt install -y < requirements.sys

## install python requirements
COPY requirements.txt requirements.txt
RUN pip3 install -U pip && \ 
    pip3 install -r requirements.txt


WORKDIR /app